// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VotacionesResidenciales.Infrastructure.Persistence;

#nullable disable

namespace VotacionesResidenciales.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528165248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.AdminConjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<Guid>("ConjuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("ConjuntoId");

                    b.ToTable("AdminesConjunto", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Conjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("Conjuntos", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.DetalleVoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpcionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotoId", "PreguntaId")
                        .IsUnique();

                    b.ToTable("DetallesVoto", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Coeficiente")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("ConjuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Piso")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Torre")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConjuntoId", "Torre", "Numero")
                        .IsUnique();

                    b.ToTable("Inmuebles", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Opcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Opciones", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VotacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotacionId");

                    b.ToTable("Preguntas", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Residente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EsPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("InmuebleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("InmuebleId");

                    b.ToTable("Residentes", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Votacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ConjuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MostrarResultadosParciales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("QuorumRequerido")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TipoPeso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Votaciones", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Voto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PesoAplicado")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("ResidenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotacionId", "ResidenteId")
                        .IsUnique();

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.AdminConjunto", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Conjunto", "Conjunto")
                        .WithMany()
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.DetalleVoto", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Voto", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Conjunto", "Conjunto")
                        .WithMany("Inmuebles")
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Opcion", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Votacion", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Residente", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Residentes")
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Voto", b =>
                {
                    b.HasOne("VotacionesResidenciales.Domain.Entities.Votacion", null)
                        .WithMany("Votos")
                        .HasForeignKey("VotacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Conjunto", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Inmueble", b =>
                {
                    b.Navigation("Residentes");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Votacion", b =>
                {
                    b.Navigation("Preguntas");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotacionesResidenciales.Domain.Entities.Voto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
